package org.suvia.trace;

public enum ModelCallScene {
    DIRECT_CHAT,
    REPORT_GENERATION,
    INTENT_CLASSIFICATION,
    QUERY_REWRITE,
    MULTI_QUERY_EXPANSION,
    RAG_ANSWER,
    AGENT_THINK,
    MEMORY_SUMMARY,
    KEYWORD_ENRICHMENT,
    EMBEDDING,
    EVALUATION_JUDGE,
    UNKNOWN
}
